### ISSUE TITLE
Read.me issure with requirements

### ISSUE THREAD

**Issue by mperacchi** [fakesimo/manga-chapter-downloader#1]
When i try to install using `pip install requirements.txt` i get this error

> ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
> ERROR: No matching distribution found for requirements.txt

Can you help me, senpai? (◕‿◕✿)

Sorry I'm new to the interweb I'm still learning how to use it

**Comment by fakesimo** [comment]
Don't worry mperacchi-chan I'm here for you  (´ ε ` )♡

Try to use `pip install -r requirements.txt`, also remember to download the selenium drivers as explained [here](https://selenium-python.readthedocs.io/installation.html#drivers)

**Comment by mperacchi** [comment]
Arigato very much sensei OwO
